server:
  port: 8301
spring:
  application:
    name: ribbon-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    register-with-eureka: true
    fetch-registry: true
service-url:
  user-service: http://user-service